---
volumes:
  pg_data_production:
  static_volume:
services:
  db:
    image: postgres:13-alpine
    env_file: .env
    volumes: [pg_data_production:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 6
      start_period: 20s
      timeout: 10s
  backend:
    image: sadomehanika/taski_backend
    env_file: .env
    volumes: [static_volume:/backend_static]
    depends_on:
      db:
        condition: service_healthy
        restart: true
  frontend:
    image: sadomehanika/taski_frontend
    env_file: .env
    volumes: [static_volume:/frontend_static]
  gateway:
    image: sadomehanika/taski_gateway
    env_file: .env
    volumes: [static_volume:/staticfiles/]
    depends_on:
      - frontend
      - backend
    ports: [8000:80]
