---
volumes:
  pg_data_production:
  static_volume:
services:
  db:
    image: postgres:13-alpine
    env_file: .env
    volumes: [pg_data_production:/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    image: sadomehanika/taski_backend
    env_file: .env
    volumes: [static_volume:/backend_static]
    depends_on:
      - db
  frontend:
    image: sadomehanika/taski_frontend
    env_file: .env
    volumes: [static_volume:/frontend_static]
  gateway:
    image: sadomehanika/taski_gateway
    env_file: .env
    volumes: [static_volume:/staticfiles/]
    depends_on:
      - frontend
      - backend
    ports: [8000:80]
